[build]
  base = "frontend"
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
  CI = "false"

# Enable Next.js runtime for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# API redirects (redirect to your backend service)
[[redirects]]
  from = "/api/*"
  to = "https://evently-p02p.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback for client-side routing (should be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"
  port = 3000
