[build]
  base = "frontend"
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
  CI = "false"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (redirect to your backend service)
[[redirects]]
  from = "/api/*"
  to = "https://evenly-backend.onrender.com/api/:splat"
  status = 200
  force = true

[dev]
  command = "pnpm run dev"
  port = 3000
